### ISSUE TITLE
Page Selector - shows page with no entries and 124

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#311] opened 2022-08-25 17:25 UTC
![image](https://user-images.githubusercontent.com/62152714/186730213-9bd2cae2-31fb-4dbd-b623-7972fac7ef4e.png)
![image](https://user-images.githubusercontent.com/62152714/186730241-92ad45bb-11b5-4e2d-ade9-102e083f69d0.png)

![image](https://user-images.githubusercontent.com/62152714/186730266-f1dc2ea8-e47c-41df-a0f6-8a7576c5a747.png)

**Comment by ppacher** [comment] 2022-08-29 07:19
The Portmaster keeps (ended) connections only for 10 minutes. This may happen when the Portmaster deletes connections after the UI loaded the total amount of pages. A simple click on "Reload" will fix that. 

I'm closing this here as this is the currently intended behavior. Once we have support for the history module (which will store connections on disk) this will not be an issue anymore.

**Closed by ppacher** 2022-08-29 07:19 UTC
Labels: bug
