### ISSUE TITLE
Portmaster 3.0 unclear requirements build failed, dependencies?

### ISSUE THREAD

**Issue by fugbixer** [safing/portmaster-ui#270] opened 2022-07-25 19:04 UTC
Portmaster 3.0 UI Build dependencies.

> 7eb0fb2 Ditch ngx-build-plus as tailwind has native support in angular now
> 79d97c6 Ditch ngx-build-plus as tailwind has native support in angular now

Okay but i tried using:

```
ng-packagr
@angular-devkit/build-angular
@angular/cli
```

which are now required to build? cant wait to see v3 :D

the missing packages are:

> @angular/common
> @angular/core
> @angular/animations
>@angular/cdk/coercio

are they part of any npm package i mentioned above or need manual install?
sadly the order in which got installed is sometimes also required to know for avoiding conflicts. 

```

> portmaster@0.3.0 build
> NODE_ENV=production ng build --configuration production @safing/ui && NODE_ENV=production ng build --configuration production --base-href /ui/modules/portmaster/ --deploy-url /ui/modules/portmaster/

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@safing/ui'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
projects/safing/ui/src/lib/animations/index.ts:1:69 - error TS2307: Cannot find module '@angular/animations' or its corresponding type declarations.

1 import { animate, query, stagger, style, transition, trigger } from '@angular/animations';
                                                                      ~~~~~~~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/accordion/accordion-group.ts:1:39 - error TS2307: Cannot find module '@angular/cdk/coercion' or its corresponding type declarations.

1 import { coerceBooleanProperty } from '@angular/cdk/coercion';
                                        ~~~~~~~~~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/accordion/accordion-group.ts:2:83 - error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.

2 import { ChangeDetectionStrategy, Component, Input, OnDestroy, TemplateRef } from '@angular/core';
                                                                                    ~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/accordion/accordion.ts:1:39 - error TS2307: Cannot find module '@angular/cdk/coercion' or its corresponding type declarations.

1 import { coerceBooleanProperty } from '@angular/cdk/coercion';
                                        ~~~~~~~~~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/accordion/accordion.ts:2:161 - error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.

2 import { ChangeDetectionStrategy, ChangeDetectorRef, Component, EventEmitter, HostBinding, Input, OnInit, Optional, Output, TemplateRef, TrackByFunction } from '@angular/core';
                                                                                                                                                                  ~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/accordion/accordion.ts:29:41 - error TS7006: Parameter '_' implicitly has an 'any' type.

29   trackBy: TrackByFunction<T | null> = (_, c) => c
                                           ~
projects/safing/ui/src/lib/accordion/accordion.ts:29:44 - error TS7006: Parameter 'c' implicitly has an 'any' type.

29   trackBy: TrackByFunction<T | null> = (_, c) => c
                                              ~
projects/safing/ui/src/lib/accordion/accordion.module.ts:1:30 - error TS2307: Cannot find module '@angular/common' or its corresponding type declarations.

1 import { CommonModule } from "@angular/common";
                               ~~~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/accordion/accordion.module.ts:2:26 - error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.

2 import { NgModule } from "@angular/core";
                           ~~~~~~~~~~~~~~~
projects/safing/ui/src/lib/dialog/dialog.animations.ts:1:60 - error TS2307: Cannot find module '@angular/animations' or its corresponding type declarations.

1 import { animate, state, style, transition, trigger } from "@angular/animations";

```

**Comment by ppacher** [comment] 2022-07-29 13:30
Hi @fugbixer,

that's interesting, i cannot reproduce your build issues.
Let's try from the beginning:

1. Enter the `modules/portmaster` folder of the repository
2. Run `npm install`
3. Run `npm run serve`
4. Open your browser to point to `http://localhost:4200`. You will also make sure to start the Portmaster in dev mode (by appending `--devmode` to the start command).

Though, the new Network Monitor (without a few pending fixes) has already been released to the `BETA`  [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel). So you should be able to get the new monitor by just chaning the setting and wait for the portmaster to detect and install the update.

**Comment by ppacher** [comment] 2022-07-29 13:33
As for the question on what packages are required for build:

`@angular/cli`: That's the angular CLI that manages the whole build of the application and the associated libraries

`ng-packagr`: Is used to create Ivy compatible libraries for `@safing/ui` and `@safing/portmaster-api`. I've moved code to those libraries because I'm experimenting with a browser extension and want to re-use the code from there.
`@angular-devkit/build-angular`: Is required to build the browser extension as I need custom webpack configuration for that to work.

**Comment by ppacher** [comment] 2022-09-15 09:50
Closing this as there wasn't any response for some time now

**Closed by ppacher** 2022-09-15 09:50 UTC
Labels: bug
