### ISSUE TITLE
Portmaster notifier stopped working well after update to 0.8.9

### ISSUE THREAD

**Issue by antonykivai** [safing/portmaster-ui#236] opened 2022-05-18 12:05 UTC
### What happened?

The portmaster notifier normally shows up in the elementary OS wingpanel.
After update to version 0.8.9, it shows an error-like icon and on clicking it does not display any of the options the notifier normally does.

![image](https://user-images.githubusercontent.com/93373534/169034191-247e2e20-77ee-42a3-89ea-1cfa4adb47f1.png)
![image](https://user-images.githubusercontent.com/93373534/169034551-b7085f8a-9318-472a-935d-90c0e26ee74d.png)

### What did you expect to happen?
The portmaster notifier to be working as expected on the wingpanel

### Additional information
Elementary OS version 6.1
Elementary wingpanel &#43; Libindicator atayana

**Debug-Info**: https://support.safing.io/privatebin/?5645aab9c36a09af#CK6yPZfTN9umVMhAq9CeTh7WQ3GSSuXqTN2feF1ebjJB

**Comment by Shaolin-Twelve** [comment] 2022-05-19 08:38
Ditto on Linux Mint 20 with Cinnamon 4.6.7. No options available on notifier, clicking it does nothing, only able to access main Portmaster interface through system menu.

**Comment by dhaavi** [comment] 2022-05-19 12:26
Hey @antonykivai and @Shaolin-Twelve, thanks a lot for reporting this.

We've recently switched from using `libappindicator` to directly talking to the dbus interface. This might be the cause of this.

To investigate, please run the notifier directly and see what it tells us:
`/opt/safing/portmaster/portmaster-start notifier`

You might need to close any open Portmaster notifier instance.

**Comment by Shaolin-Twelve** [comment] 2022-05-19 12:55
With Portmaster Notifier off.

:~$ `/opt/safing/portmaster/portmaster-start notifier`
bash: /opt/safing/portmaster/portmaster-start: No such file or directory

**Comment by Shaolin-Twelve** [comment] 2022-05-19 13:14
I could not find /opt/safing/
I did find /var/lib/portmaster/ so ran this (:~$ /var/lib/portmaster/portmaster-start notifier) in a terminal, which started the notifier but gave no output, and indicator non functional as before.

**Comment by dhaavi** [comment] 2022-05-19 14:08
Ah, yes. This is the old install location (no problem though).
It gave no output whatsoever? Weird.

**Comment by dhaavi** [comment] 2022-05-19 14:47
Out of curiousity, I would like to know if everything still works with the older notifier, that still uses libappindicator.

I've configured the _Support Release Channel_ to be just like the stable channel, but downgrade the notifier a bit. To try that, just switch the [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel) setting to `Support` and restart the notifier.

**Comment by dhaavi** [comment] 2022-05-19 15:21
It seems the library we use just fixed this issue 4 days ago in https://github.com/fyne-io/systray/commit/b479fb2893c9e86b3e8c2d2e811f1f0b5588ef10.

I've compiled with that fix and it works for me.
I just released a test version to the support channel. Can you check if that also fixes the problem for you?

It won't let you start the new notifier when the old one is still running, so either kill it or shutdown the Portmaster and start it again to get the new version running.

**Comment by Shaolin-Twelve** [comment] 2022-05-19 16:05
I have a working notifier. :-)

Below is a small selection of the terminal output when portmaster-notifier is run from the terminal.

:~$ /var/lib/portmaster/portmaster-start notifier
[control] 2022/05/19 15:56:19 starting /var/lib/portmaster/updates/linux_amd64/notifier/portmaster-notifier_v0-3-2-testtwo --data /var/lib/portmaster
220519 16:56:19.650 ▶ BOF

I was able to close this version from the tray menu also without errors, and on opening Portmaster from my system menu, the tray notifier came back up and works that way too.

**Comment by dhaavi** [comment] 2022-05-20 07:06
I have released the fix in the notifier v0.3.2 to the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel) now.

You can now get the fix by switching to the beta channel. Will be in stable soon.

The support channel is now reset again, please switch away from it.

**Comment by Shaolin-Twelve** [comment] 2022-05-20 11:49
Thank you, I have switched, awaiting stable. Top job! :-)

**Closed** 2022-06-20 05:27 UTC
Labels: bug, waiting for fix confirmation

**Comment by p2anav** [comment] 2022-06-20 09:33
Yeah, all clear, but that was a bot that automatically closed this issue.

**Comment by davegson** [comment] 2022-06-21 08:23
yeah, Daniel accidentally re-added the `waiting for fix confirmation` label after the fix was confirmed. So all good, happy this is resolved! :)
