### ISSUE TITLE
White or gray theme

### ISSUE THREAD

**Issue by akochkarev** [safing/portmaster-ui#423] opened 2023-04-19 10:43 UTC
Hi Portmasted devs! Very thanks for a cool software!

**What would you like to add or change?**:
Current UI theme is too dark for me. Especially when switching from white pages in the browser to the app UI - it hurts eyes a bit.
It will be great to have ability to switch UI theme to white or gray (less contrast then current black background).

**Why do you and others need this?**:
For more comfortable UI usage in the white backgrounded UI environment.

**Comment by dhaavi** [comment] 2023-04-20 07:20
Literally a duplicate of the last opened issue: #422

**Closed by dhaavi** 2023-04-20 07:20 UTC
Labels: suggestion
