### ISSUE TITLE
UI does not refresh...

### ISSUE THREAD

**Issue by senthilmk** [safing/portmaster-ui#424] opened 2023-04-20 03:38 UTC
Postmaster UI does not refresh automatically.  I have manually refresh to see permitted and filtered network traffic 

**What did you expect to happen?**:
UI should auto refresh every 30 seconds or some set time frequency

**How did you reproduce it?**:
This started happening about a month ago. I am running Ver 1.0.11 On Windows 11 Laptop

**Comment by dhaavi** [comment] 2023-04-20 07:23
Network traffic is not supposed to refresh.

This was the case a long time ago, but we have rebuilt the system last year and are still figuring out how to handle auto-refreshes best. If you are investigating something, you don't want the UI to throw away what you are looking at.

Closing this, as this is currently intended behavior.

**Closed by dhaavi** 2023-04-20 07:23 UTC
Labels: bug
