### ISSUE TITLE
Show Device Local and LAN separately at the Top

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#289] opened 2022-08-13 10:19 UTC
![image](https://user-images.githubusercontent.com/62152714/184479467-0839ef0b-a003-4b91-9d76-62788d12b31d.png)
![image](https://user-images.githubusercontent.com/62152714/184479513-c978d22d-0319-454a-88e5-167b03cd3480.png)

**Comment by dhaavi** [comment] 2022-08-18 13:32
Hm. Not sure about this one.
Previously we did that, but we handled many things differently in the old system.

I mean, we can definitely improve on the wording and find something better than `N/A`, but other than that, I'm not sure if there is a nice solution here.
@ppacher - what do you think?

**Comment by Rexadev** [comment] 2022-08-18 14:09
@dhaavi 
Different tint color
separate LAN and Device local
always pined at top

**Comment by ppacher** [comment] 2022-09-15 13:08
Your solution @Rexadev is not applicable here. Any connections that cannot be attributed to a domain (i.e. a preceding DNS request has been cought) will be grouped in `N/A` because there's just no domain for that. It's not only LAN/Device local. It's also for all Multicast and p2p connections. I feel like if you group by domain having an group that tells you "there's no associated domain" is the intended way. We do have that N/A for every group because there are always connections that will not be __group-able__ by all keys. 

I'm closing this here for now as I feel it's working as intended and won't change in the upcoming future.

**Closed by ppacher** 2022-09-15 13:08 UTC
Labels: bug
